##\
# This file is a part of the phpMussel\Core package.
# Homepage: https://phpmussel.github.io/
#
# PHPMUSSEL COPYRIGHT 2013 AND BEYOND BY THE PHPMUSSEL TEAM.
#
# License: GNU/GPLv2
# @see LICENSE.txt
#
# This file: Configuration defaults file (last modified: 2023.10.12).
##/

core:
 scan_log:
  type: "string"
  default: ""
 scan_log_serialized:
  type: "string"
  default: ""
 error_log:
  type: "string"
  default: ""
 outbound_request_log:
  type: "string"
  default: ""
 truncate:
  type: "kb"
  default: "0KB"
 log_rotation_limit:
  type: "int"
  default: 0
 log_rotation_action:
  type: "string"
  default: "Delete"
  choices:
   Delete: "field.log_rotation_delete"
   Archive: "field.log_rotation_archive"
  style: "radio"
 timezone:
  type: "timezone"
  default: "SYSTEM"
 time_offset:
  type: "int"
  default: 0
  preview: "minutes"
 time_format:
  type: "string"
  default: "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}"
  preview: "allow_other"
  allow_other: true
  choices:
   "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}": "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss} {tz}"
   "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss}": "{Day}, {dd} {Mon} {yyyy} {hh}:{ii}:{ss}"
   "{Day}, {dd} {Mon} {yyyy}": "{Day}, {dd} {Mon} {yyyy}"
   "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}"
   "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss}": "{yyyy}.{mm}.{dd} {hh}:{ii}:{ss}"
   "{yyyy}.{mm}.{dd}": "{yyyy}.{mm}.{dd}"
   "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}"
   "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss}": "{yyyy}-{mm}-{dd} {hh}:{ii}:{ss}"
   "{yyyy}-{mm}-{dd}": "{yyyy}-{mm}-{dd}"
   "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}": "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}"
   "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss}": "{yyyy}/{mm}/{dd} {hh}:{ii}:{ss}"
   "{yyyy}/{mm}/{dd}": "{yyyy}/{mm}/{dd}"
   "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss} {tz}"
   "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss}": "{dd}.{mm}.{yyyy} {hh}:{ii}:{ss}"
   "{dd}.{mm}.{yyyy}": "{dd}.{mm}.{yyyy}"
   "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss} {tz}"
   "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss}": "{dd}-{mm}-{yyyy} {hh}:{ii}:{ss}"
   "{dd}-{mm}-{yyyy}": "{dd}-{mm}-{yyyy}"
   "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss} {tz}": "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss} {tz}"
   "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss}": "{dd}/{mm}/{yyyy} {hh}:{ii}:{ss}"
   "{dd}/{mm}/{yyyy}": "{dd}/{mm}/{yyyy}"
   "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss} {tz}"
   "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss}": "{mm}.{dd}.{yyyy} {hh}:{ii}:{ss}"
   "{mm}.{dd}.{yyyy}": "{mm}.{dd}.{yyyy}"
   "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss} {tz}"
   "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss}": "{mm}-{dd}-{yyyy} {hh}:{ii}:{ss}"
   "{mm}-{dd}-{yyyy}": "{mm}-{dd}-{yyyy}"
   "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss} {tz}": "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss} {tz}"
   "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss}": "{mm}/{dd}/{yyyy} {hh}:{ii}:{ss}"
   "{mm}/{dd}/{yyyy}": "{mm}/{dd}/{yyyy}"
   "{yy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}": "{yy}.{mm}.{dd} {hh}:{ii}:{ss} {tz}"
   "{yy}.{mm}.{dd} {hh}:{ii}:{ss}": "{yy}.{mm}.{dd} {hh}:{ii}:{ss}"
   "{yy}.{mm}.{dd}": "{yy}.{mm}.{dd}"
   "{yy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}": "{yy}-{mm}-{dd} {hh}:{ii}:{ss} {tz}"
   "{yy}-{mm}-{dd} {hh}:{ii}:{ss}": "{yy}-{mm}-{dd} {hh}:{ii}:{ss}"
   "{yy}-{mm}-{dd}": "{yy}-{mm}-{dd}"
   "{yy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}": "{yy}/{mm}/{dd} {hh}:{ii}:{ss} {tz}"
   "{yy}/{mm}/{dd} {hh}:{ii}:{ss}": "{yy}/{mm}/{dd} {hh}:{ii}:{ss}"
   "{yy}/{mm}/{dd}": "{yy}/{mm}/{dd}"
   "{dd}.{mm}.{yy} {hh}:{ii}:{ss} {tz}": "{dd}.{mm}.{yy} {hh}:{ii}:{ss} {tz}"
   "{dd}.{mm}.{yy} {hh}:{ii}:{ss}": "{dd}.{mm}.{yy} {hh}:{ii}:{ss}"
   "{dd}.{mm}.{yy}": "{dd}.{mm}.{yy}"
   "{dd}-{mm}-{yy} {hh}:{ii}:{ss} {tz}": "{dd}-{mm}-{yy} {hh}:{ii}:{ss} {tz}"
   "{dd}-{mm}-{yy} {hh}:{ii}:{ss}": "{dd}-{mm}-{yy} {hh}:{ii}:{ss}"
   "{dd}-{mm}-{yy}": "{dd}-{mm}-{yy}"
   "{dd}/{mm}/{yy} {hh}:{ii}:{ss} {tz}": "{dd}/{mm}/{yy} {hh}:{ii}:{ss} {tz}"
   "{dd}/{mm}/{yy} {hh}:{ii}:{ss}": "{dd}/{mm}/{yy} {hh}:{ii}:{ss}"
   "{dd}/{mm}/{yy}": "{dd}/{mm}/{yy}"
   "{mm}.{dd}.{yy} {hh}:{ii}:{ss} {tz}": "{mm}.{dd}.{yy} {hh}:{ii}:{ss} {tz}"
   "{mm}.{dd}.{yy} {hh}:{ii}:{ss}": "{mm}.{dd}.{yy} {hh}:{ii}:{ss}"
   "{mm}.{dd}.{yy}": "{mm}.{dd}.{yy}"
   "{mm}-{dd}-{yy} {hh}:{ii}:{ss} {tz}": "{mm}-{dd}-{yy} {hh}:{ii}:{ss} {tz}"
   "{mm}-{dd}-{yy} {hh}:{ii}:{ss}": "{mm}-{dd}-{yy} {hh}:{ii}:{ss}"
   "{mm}-{dd}-{yy}": "{mm}-{dd}-{yy}"
   "{mm}/{dd}/{yy} {hh}:{ii}:{ss} {tz}": "{mm}/{dd}/{yy} {hh}:{ii}:{ss} {tz}"
   "{mm}/{dd}/{yy} {hh}:{ii}:{ss}": "{mm}/{dd}/{yy} {hh}:{ii}:{ss}"
   "{mm}/{dd}/{yy}": "{mm}/{dd}/{yy}"
   "{yyyy}年{m}月{d}日 {hh}時{ii}分{ss}秒": "{yyyy}年{m}月{d}日 {hh}時{ii}分{ss}秒"
   "{yyyy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}": "{yyyy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}"
   "{yyyy}年{m}月{d}日": "{yyyy}年{m}月{d}日"
   "{yy}年{m}月{d}日 {hh}時{ii}分{ss}秒": "{yy}年{m}月{d}日 {hh}時{ii}分{ss}秒"
   "{yy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}": "{yy}年{m}月{d}日 {hh}:{ii}:{ss} {tz}"
   "{yy}年{m}月{d}日": "{yy}年{m}月{d}日"
   "{yyyy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초": "{yyyy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초"
   "{yyyy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}": "{yyyy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}"
   "{yyyy}년 {m}월 {d}일": "{yyyy}년 {m}월 {d}일"
   "{yy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초": "{yy}년 {m}월 {d}일 {hh}시 {ii}분 {ss}초"
   "{yy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}": "{yy}년 {m}월 {d}일 {hh}:{ii}:{ss} {tz}"
   "{yy}년 {m}월 {d}일": "{yy}년 {m}월 {d}일"
   "{yyyy}-{mm}-{dd}T{hh}:{ii}:{ss}{t:z}": "{yyyy}-{mm}-{dd}T{hh}:{ii}:{ss}{t:z}"
   "{d}. {m}. {yyyy}": "{d}. {m}. {yyyy}"
 ipaddr:
  type: "string"
  default: "REMOTE_ADDR"
  preview: "allow_other"
  allow_other: true
  choices:
   HTTP_INCAP_CLIENT_IP: "HTTP_INCAP_CLIENT_IP (Incapsula)"
   HTTP_CF_CONNECTING_IP: "HTTP_CF_CONNECTING_IP (Cloudflare)"
   CF-Connecting-IP: "CF-Connecting-IP (Cloudflare)"
   HTTP_X_FORWARDED_FOR: "HTTP_X_FORWARDED_FOR (Cloudbric)"
   X-Forwarded-For: "X-Forwarded-For (Squid)"
   Forwarded: "Forwarded"
   REMOTE_ADDR: "REMOTE_ADDR ({label.Default})"
  See also:
   "NGINX Reverse Proxy": "https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/"
   "Squid configuration directive forwarded_for": "http://www.squid-cache.org/Doc/config/forwarded_for/"
   "Forwarded - HTTP | MDN": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded"
 delete_on_sight:
  type: "bool"
  default: false
 lang:
  type: "string"
  default: "en"
  choices:
   af: "Afrikaans"
   ar: "العربية"
   bg: "Български"
   bn: "বাংলা"
   cs: "Čeština"
   de: "Deutsch"
   en: "English (AU/GB/NZ)"
   en-CA: "English (CA)"
   en-US: "English (US)"
   es: "Español"
   fa: "فارسی"
   fr: "Français"
   he: "עברית"
   hi: "हिंदी"
   id: "Bahasa Indonesia"
   it: "Italiano"
   ja: "日本語"
   ko: "한국어"
   lv: "Latviešu"
   ms: "Bahasa Melayu"
   nl: "Nederlandse"
   no: "Norsk"
   pa: "ਪੰਜਾਬੀ"
   pl: "Polski"
   pt-BR: "Português (Brasil)"
   pt-PT: "Português (Europeu)"
   ro: "Română"
   ru: "Русский"
   sv: "Svenska"
   ta: "தமிழ்"
   th: "ภาษาไทย"
   tr: "Türkçe"
   uk: "Українська"
   ur: "اردو"
   vi: "Tiếng Việt"
   zh-CN: "中文（简体）"
   zh-TW: "中文（傳統）"
  defer:
   mo: "ro"
   nb: "no"
   zh-HK: "zh-TW"
   zh-MO: "zh-TW"
  assume:
   af: "af-ZA"
   bg: "bg-BG"
   bn: "bn-BD"
   cs: "cs-CZ"
   de: "de-DE"
   en: "en-AU"
   es: "es-ES"
   fa: "fa-IR"
   fr: "fr-FR"
   he: "he-IL"
   hi: "hi-IN"
   id: "id-ID"
   it: "it-IT"
   ja: "ja-JP"
   ko: "ko-KR"
   lv: "lv-LV"
   mo: "ro-MO"
   ms: "ms-MY"
   nb: "nb-NO"
   nl: "nl-NL"
   no: "nb-NO"
   pa: "pa-IN"
   pl: "pl-PL"
   pt: "pt-BR"
   ro: "ro-RO"
   ru: "ru-RU"
   sv: "sv-SE"
   ta: "ta-IN"
   th: "th-TH"
   tr: "tr-TR"
   uk: "uk-UA"
   ur: "ur-PK"
   vi: "vi-VN"
   zh: "zh-CN"
 lang_override:
  type: "bool"
  default: true
 scan_cache_expiry:
  type: "int"
  default: 21600
  preview: "seconds"
 maintenance_mode:
  type: "bool"
  default: false
 statistics:
  type: "bool"
  default: false
 hide_version:
  type: "bool"
  default: false
 disabled_channels:
  type: "checkbox"
  default: "VirusTotal_HTTP"
  choices:
   GitHub: "GitHub"
   BitBucket: "BitBucket"
   VirusTotal_HTTPS: "VirusTotal (HTTPS)"
   VirusTotal_HTTP: "VirusTotal (HTTP)"
  value_preg_filter:
   "~\s~": ""
 default_timeout:
  type: "int"
  default: 12
  preview: "seconds"
signatures:
 active:
  type: "string"
  default: "clamav.cedb,clamav.db,clamav.fdb,clamav.hdb,clamav.htdb,clamav.mdb,clamav.ndb,clamav_elf.db,clamav_elf_regex.db,clamav_email.db,clamav_email_regex.db,clamav_exe.db,clamav_exe_regex.db,clamav_graphics.db,clamav_graphics_regex.db,clamav_java.db,clamav_java_regex.db,clamav_macho.db,clamav_macho_regex.db,clamav_ole.db,clamav_ole_regex.db,clamav_pdf.db,clamav_pdf_regex.db,clamav_regex.db,clamav_regex.htdb,clamav_regex.ndb,clamav_swf.db,clamav_swf_regex.db,phpmussel.cedb,phpmussel.db,phpmussel.fdb,phpmussel.hdb,phpmussel.htdb,phpmussel.mdb,phpmussel.medb,phpmussel.ndb,phpmussel.udb,phpmussel_elf.db,phpmussel_email.db,phpmussel_email_regex.db,phpmussel_exe.db,phpmussel_exe_regex.db,phpmussel_graphics.db,phpmussel_graphics_regex.db,phpmussel_ole.db,phpmussel_ole_regex.db,phpmussel_pdf.db,phpmussel_regex.db,phpmussel_regex.htdb,phpmussel_regex.ndb,phpmussel_swf.db,phpmussel_swf_regex.db"
  value_preg_filter:
   "~\s~": ""
 fail_silently:
  type: "bool"
  default: true
 fail_extensions_silently:
  type: "bool"
  default: true
 detect_adware:
  type: "bool"
  default: true
 detect_joke_hoax:
  type: "bool"
  default: true
 detect_pua_pup:
  type: "bool"
  default: true
 detect_packer_packed:
  type: "bool"
  default: true
 detect_shell:
  type: "bool"
  default: true
 detect_deface:
  type: "bool"
  default: true
 detect_encryption:
  type: "bool"
  default: true
 heuristic_threshold:
  type: "int"
  default: 3
files:
 filesize_limit:
  type: "kb"
  default: "64MB"
 filesize_response:
  type: "bool"
  default: true
 filetype_whitelist:
  type: "string"
  default: ""
  value_preg_filter:
   "~\s~": ""
  hints: "hints_xlists"
 filetype_blacklist:
  type: "string"
  default: "386,acc*,acm,act*,apk,app,ash*,asm*,asx*,ax,bat,bin,ccc,cgi,cmd,com*,cpl,cpp,csh,dll,drv,elf,exe,fxp,gad*,hta*,htp*,ico,inf,ins,inx,ipa,isu,job,js,jse,ksh,lnk,msc,msi,msp,mst,net,ocx,ops,org,osx,out,paf,php*,pif,pl,prg,ps1,reg,rgs,rs,run,scr*,sct,shb,shs,sql*,sys,u3p,url,vb,vbe,vbs*,wor*,ws,wsf,xsl"
  value_preg_filter:
   "~\s~": ""
  hints: "hints_xlists"
 filetype_greylist:
  type: "string"
  default: ""
  value_preg_filter:
   "~\s~": ""
  hints: "hints_xlists"
 check_archives:
  type: "bool"
  default: true
 filesize_archives:
  type: "bool"
  default: true
 filetype_archives:
  type: "bool"
  default: false
 max_recursion:
  type: "int"
  default: 3
 block_encrypted_archives:
  type: "bool"
  default: true
 max_files_in_archives:
  type: "int"
  default: 0
 chameleon_from_php:
  type: "bool"
  default: true
 can_contain_php_file_extensions:
  type: "string"
  default: "inc,md,phar,php*,pzp,sig,tpl,txt,tzt"
  value_preg_filter:
   "~\s~": ""
 chameleon_from_exe:
  type: "bool"
  default: true
 chameleon_to_archive:
  type: "bool"
  default: true
 chameleon_to_doc:
  type: "bool"
  default: true
 chameleon_to_img:
  type: "bool"
  default: true
 chameleon_to_pdf:
  type: "bool"
  default: true
 archive_file_extensions:
  type: "string"
  default: "7z,a,ace,alz,apk,app,ar,arc,arj,ba,bh,bz,bz2,dmg,gz,ice,iso,lha,lz,lzh,lzo,lzw,lzx,mar,pak,pck,pea,phar,rar,rz,s7z,sea,sen,sfx,shar,sqx,tar,tgz,tlz,xar,xp3,xz,yz1,z,zz,paq*,sit*,tbz*,zip*"
  value_preg_filter:
   "~\s~": ""
 block_control_characters:
  type: "bool"
  default: false
 corrupted_exe:
  type: "bool"
  default: true
 decode_threshold:
  type: "kb"
  default: "512KB"
 scannable_threshold:
  type: "kb"
  default: "32MB"
 allow_leading_trailing_dots:
  type: "bool"
  default: false
 block_macros:
  type: "bool"
  default: false
  experimental: true
 only_allow_images:
  type: "bool"
  default: false
quarantine:
 quarantine_key:
  type: "string"
  default: ""
 quarantine_max_filesize:
  type: "kb"
  default: "2MB"
 quarantine_max_usage:
  type: "kb"
  default: "64MB"
 quarantine_max_files:
  type: "int"
  default: 100
virustotal:
 vt_public_api_key:
  type: "string"
  default: ""
  See also:
   Terms of Service: "https://www.virustotal.com/en/about/terms-of-service/"
   Getting started: "https://developers.virustotal.com/reference"
 vt_suspicion_level:
  type: "int"
  default: 1
  choices:
   0: "field.vt_suspicion_level_heuristic_only"
   1: "field.vt_suspicion_level_executable"
   2: "field.vt_suspicion_level_all"
  style: "radio"
 vt_weighting:
  type: "int"
  default: 0
 vt_quota_rate:
  type: "int"
  default: 4
 vt_quota_time:
  type: "int"
  default: 1
  preview: "minutes"
urlscanner:
 google_api_key:
  type: "string"
  default: ""
  See also:
   Google API Console: "https://console.developers.google.com/"
 maximum_api_lookups:
  type: "int"
  default: 10
 maximum_api_lookups_response:
  type: "bool"
  default: false
 cache_time:
  type: "int"
  default: 3600
  preview: "seconds"
legal:
 pseudonymise_ip_addresses:
  type: "bool"
  default: true
supplementary_cache_options:
 prefix:
  type: "string"
  default: "phpMussel_"
 enable_apcu:
  type: "bool"
  default: true
  required:
   apcu: "APCu"
 enable_memcached:
  type: "bool"
  default: false
  required:
   memcached: "Memcached"
 enable_redis:
  type: "bool"
  default: false
  required:
   redis: "Redis"
 enable_pdo:
  type: "bool"
  default: false
  required:
   pdo: "PDO"
 memcached_host:
  type: "string"
  default: "localhost"
 memcached_port:
  type: "int"
  default: 11211
  min: 0
  max: 65535
 redis_host:
  type: "string"
  default: "localhost"
 redis_port:
  type: "int"
  default: 6379
  min: 0
  max: 65535
 redis_timeout:
  type: "float"
  step: "any"
  default: 2.5
 pdo_dsn:
  type: "string"
  default: "mysql:dbname=phpmussel;host=localhost;port=3306"
  hints: "hints_pdo_dsn"
 pdo_username:
  type: "string"
  default: ""
  autocomplete: "username"
 pdo_password:
  type: "string"
  default: ""
  autocomplete: "current-password"
